# Generated by Django 3.1.3 on 2020-12-08 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c4045c05-ff96-469f-b0b9-edf867f6d78d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ksiazka',
            name='id',
            field=models.UUIDField(default=uuid.UUID('509d28bb-5c1b-4e60-9f2c-4bda48b29b82'), editable=False, primary_key=True, serialize=False),
        ),
    ]
