# Generated by Django 3.1.3 on 2020-12-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20201222_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='data_wydania',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
