# Generated by Django 3.1.3 on 2020-12-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20201223_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ksiazka',
            options={'permissions': (('can_add', 'Dodanie ksiazki'),)},
        ),
    ]
