from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys
from pynput.mouse import Button, Controller
import pynput.keyboard
browser=webdriver.Chrome()
browser.maximize_window()
browser.get('https://pl4.forgeofempires.com/game/index?ref=')
browser.find_element_by_id("login_userid").send_keys('')
browser.find_element_by_id("login_password").send_keys('')
browser.find_element_by_id("login_Login").click()
time.sleep(4)
browser.find_element_by_class_name("play_button").click()
time.sleep(2)
browser.find_element_by_link_text("Dinegu").click()
time.sleep(25)

mouse = Controller()
mouse.position = (1098, 224)
mouse.click(Button.left, 1)
time.sleep(2)
keyboard = pynput.keyboard.Controller()
x = 1
print(time.ctime())
while True:
    print("Pętla: ", x, "---", x*57)
    x+=1
    mouse.position = (650, 259)
    time.sleep(1)
    mouse.click(Button.left, 1)
    time.sleep(3)
    mouse.click(Button.left, 1)
    time.sleep(1)
    mouse.position = (481, 441)
    time.sleep(3)
    mouse.click(Button.left, 1)
    time.sleep(1)

    mouse.position = (436, 348)
    time.sleep(1)
    mouse.click(Button.left, 1)
    time.sleep(3)
    mouse.click(Button.left, 1)
    time.sleep(1)
    mouse.position = (484, 444)
    time.sleep(3)
    mouse.click(Button.left, 1)
    time.sleep(1)

    mouse.position = (619, 433)
    time.sleep(1)
    mouse.click(Button.left, 1)
    time.sleep(3)
    mouse.click(Button.left, 1)
    time.sleep(1)
    mouse.position = (481, 443)
    time.sleep(3)
    mouse.click(Button.left, 1)
    time.sleep(1)

    mouse.position = (697, 519)
    time.sleep(1)
    mouse.click(Button.left, 1)
    time.sleep(3)
    mouse.click(Button.left, 1)
    time.sleep(1)
    mouse.position = (481, 441)
    time.sleep(3)
    mouse.click(Button.left, 1)
    time.sleep(1)
    with keyboard.pressed(pynput.keyboard.Key.alt):
        keyboard.press(pynput.keyboard.Key.tab)
        time.sleep(0.01)
        keyboard.release(pynput.keyboard.Key.tab)
    time.sleep(300)
    with keyboard.pressed(pynput.keyboard.Key.alt):
        keyboard.press(pynput.keyboard.Key.tab)
        time.sleep(0.01)
        keyboard.release(pynput.keyboard.Key.tab)
    time.sleep(2)
#    keyboard.press(pynput.keyboard.Key.cmd)
#    time.sleep(0.01)
#    keyboard.release(pynput.keyboard.Key.cmd)
#    time.sleep(2)
