# Generated by Django 3.1.3 on 2020-12-09 16:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2b11807f-38b8-42bd-9976-df422c2a2a93'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='computer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2b876492-23d9-4986-b4da-b1f45aaa6ade'), editable=False, primary_key=True, serialize=False),
        ),
    ]
