# Generated by Django 3.1.3 on 2020-12-22 18:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20201215_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='WypozyczonaKsiazka',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('data_zwrotu', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('d', 'Dostepna'), ('w', 'Wypozyczona')], default='d', max_length=1)),
                ('ksiazka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.ksiazka')),
            ],
        ),
    ]
